### ISSUE TITLE
Error: TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by juergenbr** [EndBug/version-check#29] opened 2020-10-10 07:29 UTC
Hi, I was looking for a way to detect version changes to send automatic tweets whenever a new release is created.
This action seems to do exactly what I need, but unfortunately I run across the following error when testing it:
`Error: TypeError: Cannot read property 'id' of undefined`
You can check the test run [here](https://github.com/juergenbr/html-template/runs/1228145281?check_suite_focus=true).

Could you give me a hint what I'm doing wrong?

**Comment by EndBug** [comment] 2020-10-10 08:06
I think that the problem is the list of events you're making it run for. The action works bu "scanning" the commits that have been pushed, but
- the `release` event is not technically pushing any commit
- when you `push` tags you're not pushing any commit
For the action, that means it's searching in 0 commits, as it says in [this line](https://github.com/juergenbr/html-template/runs/1228145281?check_suite_focus=true#step:5:5).

What I can suggest you to do is something like [this](https://github.com/EndBug/version-check#static-checking-with-your-latest-version-on-npm): you can use `static-checking` and a `file-url` to check whether the version has changed on every `release` event.
The only thing is that you need to somehow get the URL of the latest version before the release you're running. One thing you could do is running this before actually publishing it to npm: this way you could use an URL like `https://unpkg.com/your-package@latest/package.json`, because `latest` would still point to your previous version.

You could set it up so that, every time you publish a new release on GitHub:
- this whole part runs, and the tweet is sent
- then you run a job that publishes it npm or gpr, or both

If you need an example to set up auto-publishing workflow, take a look at [this](https://github.com/dbots-pkg/dbots.js/blob/master/.github/workflows/release.yml).
Whenever I publish a new release on GitHub:
- I do some chores: in my case I update the tags an the docs, but in yours it would be tweeting about the release
- After that, I concurrently tart the publishing on both npm and gpr.

I hope this helps, let me know if something's not clear ;)

**Comment by juergenbr** [comment] 2020-10-10 10:47
Thanks for the detailed reply, that helped a lot! I suspected that pulling the tweet action out of the main release workflow might cause a problem. I just tested with version-check running right after creating the pull request, and this is working.

**Comment by EndBug** [comment] 2020-10-10 10:51
Awesome! I'll close this issue for now, feel free to open a new one if you have any other question 😄

**Closed by EndBug** 2020-10-10 10:51 UTC
Labels: type: question
