### ISSUE TITLE
[Feature] file-name can be dynamic link to support version from npm registry

### ISSUE THREAD

**Issue by CJY0208** [EndBug/version-check#17] opened 2020-06-30 11:46 UTC
Hello! 

I want to compare the version of the github package with the remote package from npm registry so that I can control the timing of the action more precisely.

But it does not seem to support it at present.

Is it possible to support this feature? For example the following usage.

```txt
with:
  file-name: "https://unpkg.com/#{package name here}/package.json"
```

Thank!

**Comment by EndBug** [comment] 2020-06-30 19:50
Hi, thanks for the issue! I've updated the `master` branch with two new arguments that you could use for your purpose: 
- `file-url`: you can use this to link the `package.json`
- `assume-same-version`: you can use this to set which of the version (`new` or `old`) to overwrite with the one from your file

You can find more info about those in the README. It would be awesome if you could test this for your specific case: you can use  either `EndBug/version-check@master` or `EndBug/version-check@2f6e70141b2a2c334bf38d2e3578f5f68a9060ab`.
I've done some test, but please let me know if everything works as intended: if everything's fine, I'll publish a minor version update ;)

**Comment by CJY0208** [comment] 2020-07-01 02:23
Efficient response speed!

I tried in my personal project, but failed to achieve the desired result

After I set `file-url`, `version-check` still seems to require me to include `package.json / version` changes in commits

What I expect is that after setting the `file-url`, only the latest version number in the warehouse is used to directly compare with the remote end, but at present it is still necessary to change the `package.json` of the local warehouse

Is it the wrong way I use it?

The following is my history of `actions`. The entry in the list named "Realease 0.0.0-beta.3" is the part I published after trying to compare the remote versions
https://github.com/szfe/szfe-ui/actions

**Comment by EndBug** [comment] 2020-07-01 13:31
I've added another argument: `static-checking`. This will just check the two versions without worrying about the actual commits; you'll have to say which one is supposed to be the newest, more about that in the README

Could you please test it one more time?

**Comment by CJY0208** [comment] 2020-07-01 14:05
It works :D  Thank very well!

The current usage has met my scene needs, thank you very much. :D

And I noticed that when I did not provide the `file-name`, I encountered the following error.

```txt
Static-checking files...
  Package file name: "."
  Package file URL: "https://unpkg.com/szfe-ui/package.json"
  ##[error]EISDIR: illegal operation on a directory, read
```

**Comment by EndBug** [comment] 2020-07-01 15:42
Thanks! Please try one more time without the file name, it should be fixed now

**Comment by CJY0208** [comment] 2020-07-02 01:37
Yes, works well without `file-name` opt now. Perfect

**Comment by EndBug** [comment] 2020-07-03 15:33
(Forgot to say it here yesterday)
These changes have been published in version `v1.4.0` (you can also use `v1`)
I'm closing this issue for now

**Closed by EndBug** 2020-07-03 15:33 UTC
Labels: enhancement, good first issue

**Comment by CJY0208** [comment] 2020-07-03 15:34
Thank very much :D

**Comment by EndBug** [comment] 2020-07-13 10:18
@all-contributors please add @CJY0208 for ideas
